packages:
  - "apps/**"
  - "packages/**"
  - "!apps/backend/.medusa/**"

# pnpm 11+
allowBuilds:
  "@medusajs/telemetry": true
  "@swc/core": true
  esbuild: true
  msgpackr-extract: true
  protobufjs: true
  sharp: true
  unrs-resolver: true

# pnpm 10.x
onlyBuiltDependencies:
  - "@medusajs/telemetry"
  - "@swc/core"
  - esbuild
  - msgpackr-extract
  - protobufjs
  - sharp
  - unrs-resolver
